// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameMain2.proto

package com.ma.test.protobuf;

public interface gamedata2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:gamedata2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
   */
  java.util.List<com.ma.test.protobuf.gamedata2.gamedata1> 
      getDatasList();
  /**
   * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
   */
  com.ma.test.protobuf.gamedata2.gamedata1 getDatas(int index);
  /**
   * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
   */
  int getDatasCount();
  /**
   * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
   */
  java.util.List<? extends com.ma.test.protobuf.gamedata2.gamedata1OrBuilder> 
      getDatasOrBuilderList();
  /**
   * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
   */
  com.ma.test.protobuf.gamedata2.gamedata1OrBuilder getDatasOrBuilder(
      int index);
}
