// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameMain.proto

package com.ma.test.protobuf;

/**
 * Protobuf type {@code gamedata}
 */
public  final class gamedata extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gamedata)
    gamedataOrBuilder {
  // Use gamedata.newBuilder() to construct.
  private gamedata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private gamedata() {
    row_ = 0;
    column_ = 0;
    data_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private gamedata(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            row_ = input.readInt32();
            break;
          }
          case 16: {

            column_ = input.readInt32();
            break;
          }
          case 24: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              data_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000004;
            }
            data_.add(input.readInt32());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
              data_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000004;
            }
            while (input.getBytesUntilLimit() > 0) {
              data_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        data_ = java.util.Collections.unmodifiableList(data_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ma.test.protobuf.GameMain.internal_static_gamedata_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ma.test.protobuf.GameMain.internal_static_gamedata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ma.test.protobuf.gamedata.class, com.ma.test.protobuf.gamedata.Builder.class);
  }

  private int bitField0_;
  public static final int ROW_FIELD_NUMBER = 1;
  private int row_;
  /**
   * <code>int32 row = 1;</code>
   */
  public int getRow() {
    return row_;
  }

  public static final int COLUMN_FIELD_NUMBER = 2;
  private int column_;
  /**
   * <code>int32 column = 2;</code>
   */
  public int getColumn() {
    return column_;
  }

  public static final int DATA_FIELD_NUMBER = 3;
  private java.util.List<java.lang.Integer> data_;
  /**
   * <code>repeated int32 data = 3;</code>
   */
  public java.util.List<java.lang.Integer>
      getDataList() {
    return data_;
  }
  /**
   * <code>repeated int32 data = 3;</code>
   */
  public int getDataCount() {
    return data_.size();
  }
  /**
   * <code>repeated int32 data = 3;</code>
   */
  public int getData(int index) {
    return data_.get(index);
  }
  private int dataMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (row_ != 0) {
      output.writeInt32(1, row_);
    }
    if (column_ != 0) {
      output.writeInt32(2, column_);
    }
    if (getDataList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(dataMemoizedSerializedSize);
    }
    for (int i = 0; i < data_.size(); i++) {
      output.writeInt32NoTag(data_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (row_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, row_);
    }
    if (column_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, column_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < data_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(data_.get(i));
      }
      size += dataSize;
      if (!getDataList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      dataMemoizedSerializedSize = dataSize;
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ma.test.protobuf.gamedata)) {
      return super.equals(obj);
    }
    com.ma.test.protobuf.gamedata other = (com.ma.test.protobuf.gamedata) obj;

    boolean result = true;
    result = result && (getRow()
        == other.getRow());
    result = result && (getColumn()
        == other.getColumn());
    result = result && getDataList()
        .equals(other.getDataList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROW_FIELD_NUMBER;
    hash = (53 * hash) + getRow();
    hash = (37 * hash) + COLUMN_FIELD_NUMBER;
    hash = (53 * hash) + getColumn();
    if (getDataCount() > 0) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getDataList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ma.test.protobuf.gamedata parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ma.test.protobuf.gamedata parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ma.test.protobuf.gamedata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ma.test.protobuf.gamedata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ma.test.protobuf.gamedata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ma.test.protobuf.gamedata parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ma.test.protobuf.gamedata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ma.test.protobuf.gamedata parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ma.test.protobuf.gamedata parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ma.test.protobuf.gamedata parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ma.test.protobuf.gamedata parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ma.test.protobuf.gamedata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ma.test.protobuf.gamedata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gamedata}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gamedata)
      com.ma.test.protobuf.gamedataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ma.test.protobuf.GameMain.internal_static_gamedata_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ma.test.protobuf.GameMain.internal_static_gamedata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ma.test.protobuf.gamedata.class, com.ma.test.protobuf.gamedata.Builder.class);
    }

    // Construct using com.ma.test.protobuf.gamedata.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      row_ = 0;

      column_ = 0;

      data_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ma.test.protobuf.GameMain.internal_static_gamedata_descriptor;
    }

    public com.ma.test.protobuf.gamedata getDefaultInstanceForType() {
      return com.ma.test.protobuf.gamedata.getDefaultInstance();
    }

    public com.ma.test.protobuf.gamedata build() {
      com.ma.test.protobuf.gamedata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.ma.test.protobuf.gamedata buildPartial() {
      com.ma.test.protobuf.gamedata result = new com.ma.test.protobuf.gamedata(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.row_ = row_;
      result.column_ = column_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        data_ = java.util.Collections.unmodifiableList(data_);
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.data_ = data_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ma.test.protobuf.gamedata) {
        return mergeFrom((com.ma.test.protobuf.gamedata)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ma.test.protobuf.gamedata other) {
      if (other == com.ma.test.protobuf.gamedata.getDefaultInstance()) return this;
      if (other.getRow() != 0) {
        setRow(other.getRow());
      }
      if (other.getColumn() != 0) {
        setColumn(other.getColumn());
      }
      if (!other.data_.isEmpty()) {
        if (data_.isEmpty()) {
          data_ = other.data_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureDataIsMutable();
          data_.addAll(other.data_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ma.test.protobuf.gamedata parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ma.test.protobuf.gamedata) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int row_ ;
    /**
     * <code>int32 row = 1;</code>
     */
    public int getRow() {
      return row_;
    }
    /**
     * <code>int32 row = 1;</code>
     */
    public Builder setRow(int value) {
      
      row_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 row = 1;</code>
     */
    public Builder clearRow() {
      
      row_ = 0;
      onChanged();
      return this;
    }

    private int column_ ;
    /**
     * <code>int32 column = 2;</code>
     */
    public int getColumn() {
      return column_;
    }
    /**
     * <code>int32 column = 2;</code>
     */
    public Builder setColumn(int value) {
      
      column_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 column = 2;</code>
     */
    public Builder clearColumn() {
      
      column_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> data_ = java.util.Collections.emptyList();
    private void ensureDataIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        data_ = new java.util.ArrayList<java.lang.Integer>(data_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated int32 data = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getDataList() {
      return java.util.Collections.unmodifiableList(data_);
    }
    /**
     * <code>repeated int32 data = 3;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated int32 data = 3;</code>
     */
    public int getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated int32 data = 3;</code>
     */
    public Builder setData(
        int index, int value) {
      ensureDataIsMutable();
      data_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 data = 3;</code>
     */
    public Builder addData(int value) {
      ensureDataIsMutable();
      data_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 data = 3;</code>
     */
    public Builder addAllData(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureDataIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, data_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 data = 3;</code>
     */
    public Builder clearData() {
      data_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:gamedata)
  }

  // @@protoc_insertion_point(class_scope:gamedata)
  private static final com.ma.test.protobuf.gamedata DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ma.test.protobuf.gamedata();
  }

  public static com.ma.test.protobuf.gamedata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<gamedata>
      PARSER = new com.google.protobuf.AbstractParser<gamedata>() {
    public gamedata parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new gamedata(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<gamedata> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<gamedata> getParserForType() {
    return PARSER;
  }

  public com.ma.test.protobuf.gamedata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

