// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameControl.proto

package com.ma.test.protobuf;

public interface gameinputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gameinput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();
}
