// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameMain2.proto

package com.ma.test.protobuf;

/**
 * Protobuf type {@code gamedata2}
 */
public  final class gamedata2 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gamedata2)
    gamedata2OrBuilder {
  // Use gamedata2.newBuilder() to construct.
  private gamedata2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private gamedata2() {
    datas_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private gamedata2(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              datas_ = new java.util.ArrayList<com.ma.test.protobuf.gamedata2.gamedata1>();
              mutable_bitField0_ |= 0x00000001;
            }
            datas_.add(
                input.readMessage(com.ma.test.protobuf.gamedata2.gamedata1.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        datas_ = java.util.Collections.unmodifiableList(datas_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ma.test.protobuf.GameMain2.internal_static_gamedata2_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ma.test.protobuf.GameMain2.internal_static_gamedata2_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ma.test.protobuf.gamedata2.class, com.ma.test.protobuf.gamedata2.Builder.class);
  }

  public interface gamedata1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:gamedata2.gamedata1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 data = 1;</code>
     */
    java.util.List<java.lang.Integer> getDataList();
    /**
     * <code>repeated int32 data = 1;</code>
     */
    int getDataCount();
    /**
     * <code>repeated int32 data = 1;</code>
     */
    int getData(int index);
  }
  /**
   * Protobuf type {@code gamedata2.gamedata1}
   */
  public  static final class gamedata1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gamedata2.gamedata1)
      gamedata1OrBuilder {
    // Use gamedata1.newBuilder() to construct.
    private gamedata1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private gamedata1() {
      data_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private gamedata1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                data_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                data_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                data_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ma.test.protobuf.GameMain2.internal_static_gamedata2_gamedata1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ma.test.protobuf.GameMain2.internal_static_gamedata2_gamedata1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ma.test.protobuf.gamedata2.gamedata1.class, com.ma.test.protobuf.gamedata2.gamedata1.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> data_;
    /**
     * <code>repeated int32 data = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getDataList() {
      return data_;
    }
    /**
     * <code>repeated int32 data = 1;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated int32 data = 1;</code>
     */
    public int getData(int index) {
      return data_.get(index);
    }
    private int dataMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getDataList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(dataMemoizedSerializedSize);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeInt32NoTag(data_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < data_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(data_.get(i));
        }
        size += dataSize;
        if (!getDataList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        dataMemoizedSerializedSize = dataSize;
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ma.test.protobuf.gamedata2.gamedata1)) {
        return super.equals(obj);
      }
      com.ma.test.protobuf.gamedata2.gamedata1 other = (com.ma.test.protobuf.gamedata2.gamedata1) obj;

      boolean result = true;
      result = result && getDataList()
          .equals(other.getDataList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ma.test.protobuf.gamedata2.gamedata1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ma.test.protobuf.gamedata2.gamedata1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ma.test.protobuf.gamedata2.gamedata1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ma.test.protobuf.gamedata2.gamedata1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ma.test.protobuf.gamedata2.gamedata1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ma.test.protobuf.gamedata2.gamedata1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ma.test.protobuf.gamedata2.gamedata1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ma.test.protobuf.gamedata2.gamedata1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ma.test.protobuf.gamedata2.gamedata1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ma.test.protobuf.gamedata2.gamedata1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ma.test.protobuf.gamedata2.gamedata1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ma.test.protobuf.gamedata2.gamedata1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ma.test.protobuf.gamedata2.gamedata1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gamedata2.gamedata1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gamedata2.gamedata1)
        com.ma.test.protobuf.gamedata2.gamedata1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ma.test.protobuf.GameMain2.internal_static_gamedata2_gamedata1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ma.test.protobuf.GameMain2.internal_static_gamedata2_gamedata1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ma.test.protobuf.gamedata2.gamedata1.class, com.ma.test.protobuf.gamedata2.gamedata1.Builder.class);
      }

      // Construct using com.ma.test.protobuf.gamedata2.gamedata1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ma.test.protobuf.GameMain2.internal_static_gamedata2_gamedata1_descriptor;
      }

      public com.ma.test.protobuf.gamedata2.gamedata1 getDefaultInstanceForType() {
        return com.ma.test.protobuf.gamedata2.gamedata1.getDefaultInstance();
      }

      public com.ma.test.protobuf.gamedata2.gamedata1 build() {
        com.ma.test.protobuf.gamedata2.gamedata1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ma.test.protobuf.gamedata2.gamedata1 buildPartial() {
        com.ma.test.protobuf.gamedata2.gamedata1 result = new com.ma.test.protobuf.gamedata2.gamedata1(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ma.test.protobuf.gamedata2.gamedata1) {
          return mergeFrom((com.ma.test.protobuf.gamedata2.gamedata1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ma.test.protobuf.gamedata2.gamedata1 other) {
        if (other == com.ma.test.protobuf.gamedata2.gamedata1.getDefaultInstance()) return this;
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ma.test.protobuf.gamedata2.gamedata1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ma.test.protobuf.gamedata2.gamedata1) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> data_ = java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = new java.util.ArrayList<java.lang.Integer>(data_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 data = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getDataList() {
        return java.util.Collections.unmodifiableList(data_);
      }
      /**
       * <code>repeated int32 data = 1;</code>
       */
      public int getDataCount() {
        return data_.size();
      }
      /**
       * <code>repeated int32 data = 1;</code>
       */
      public int getData(int index) {
        return data_.get(index);
      }
      /**
       * <code>repeated int32 data = 1;</code>
       */
      public Builder setData(
          int index, int value) {
        ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 data = 1;</code>
       */
      public Builder addData(int value) {
        ensureDataIsMutable();
        data_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 data = 1;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 data = 1;</code>
       */
      public Builder clearData() {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:gamedata2.gamedata1)
    }

    // @@protoc_insertion_point(class_scope:gamedata2.gamedata1)
    private static final com.ma.test.protobuf.gamedata2.gamedata1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ma.test.protobuf.gamedata2.gamedata1();
    }

    public static com.ma.test.protobuf.gamedata2.gamedata1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<gamedata1>
        PARSER = new com.google.protobuf.AbstractParser<gamedata1>() {
      public gamedata1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new gamedata1(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<gamedata1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<gamedata1> getParserForType() {
      return PARSER;
    }

    public com.ma.test.protobuf.gamedata2.gamedata1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int DATAS_FIELD_NUMBER = 1;
  private java.util.List<com.ma.test.protobuf.gamedata2.gamedata1> datas_;
  /**
   * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
   */
  public java.util.List<com.ma.test.protobuf.gamedata2.gamedata1> getDatasList() {
    return datas_;
  }
  /**
   * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
   */
  public java.util.List<? extends com.ma.test.protobuf.gamedata2.gamedata1OrBuilder> 
      getDatasOrBuilderList() {
    return datas_;
  }
  /**
   * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
   */
  public int getDatasCount() {
    return datas_.size();
  }
  /**
   * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
   */
  public com.ma.test.protobuf.gamedata2.gamedata1 getDatas(int index) {
    return datas_.get(index);
  }
  /**
   * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
   */
  public com.ma.test.protobuf.gamedata2.gamedata1OrBuilder getDatasOrBuilder(
      int index) {
    return datas_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < datas_.size(); i++) {
      output.writeMessage(1, datas_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < datas_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, datas_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ma.test.protobuf.gamedata2)) {
      return super.equals(obj);
    }
    com.ma.test.protobuf.gamedata2 other = (com.ma.test.protobuf.gamedata2) obj;

    boolean result = true;
    result = result && getDatasList()
        .equals(other.getDatasList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDatasCount() > 0) {
      hash = (37 * hash) + DATAS_FIELD_NUMBER;
      hash = (53 * hash) + getDatasList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ma.test.protobuf.gamedata2 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ma.test.protobuf.gamedata2 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ma.test.protobuf.gamedata2 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ma.test.protobuf.gamedata2 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ma.test.protobuf.gamedata2 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ma.test.protobuf.gamedata2 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ma.test.protobuf.gamedata2 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ma.test.protobuf.gamedata2 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ma.test.protobuf.gamedata2 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ma.test.protobuf.gamedata2 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ma.test.protobuf.gamedata2 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ma.test.protobuf.gamedata2 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ma.test.protobuf.gamedata2 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gamedata2}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gamedata2)
      com.ma.test.protobuf.gamedata2OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ma.test.protobuf.GameMain2.internal_static_gamedata2_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ma.test.protobuf.GameMain2.internal_static_gamedata2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ma.test.protobuf.gamedata2.class, com.ma.test.protobuf.gamedata2.Builder.class);
    }

    // Construct using com.ma.test.protobuf.gamedata2.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDatasFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (datasBuilder_ == null) {
        datas_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        datasBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ma.test.protobuf.GameMain2.internal_static_gamedata2_descriptor;
    }

    public com.ma.test.protobuf.gamedata2 getDefaultInstanceForType() {
      return com.ma.test.protobuf.gamedata2.getDefaultInstance();
    }

    public com.ma.test.protobuf.gamedata2 build() {
      com.ma.test.protobuf.gamedata2 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.ma.test.protobuf.gamedata2 buildPartial() {
      com.ma.test.protobuf.gamedata2 result = new com.ma.test.protobuf.gamedata2(this);
      int from_bitField0_ = bitField0_;
      if (datasBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          datas_ = java.util.Collections.unmodifiableList(datas_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.datas_ = datas_;
      } else {
        result.datas_ = datasBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ma.test.protobuf.gamedata2) {
        return mergeFrom((com.ma.test.protobuf.gamedata2)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ma.test.protobuf.gamedata2 other) {
      if (other == com.ma.test.protobuf.gamedata2.getDefaultInstance()) return this;
      if (datasBuilder_ == null) {
        if (!other.datas_.isEmpty()) {
          if (datas_.isEmpty()) {
            datas_ = other.datas_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDatasIsMutable();
            datas_.addAll(other.datas_);
          }
          onChanged();
        }
      } else {
        if (!other.datas_.isEmpty()) {
          if (datasBuilder_.isEmpty()) {
            datasBuilder_.dispose();
            datasBuilder_ = null;
            datas_ = other.datas_;
            bitField0_ = (bitField0_ & ~0x00000001);
            datasBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDatasFieldBuilder() : null;
          } else {
            datasBuilder_.addAllMessages(other.datas_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ma.test.protobuf.gamedata2 parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ma.test.protobuf.gamedata2) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.ma.test.protobuf.gamedata2.gamedata1> datas_ =
      java.util.Collections.emptyList();
    private void ensureDatasIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        datas_ = new java.util.ArrayList<com.ma.test.protobuf.gamedata2.gamedata1>(datas_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ma.test.protobuf.gamedata2.gamedata1, com.ma.test.protobuf.gamedata2.gamedata1.Builder, com.ma.test.protobuf.gamedata2.gamedata1OrBuilder> datasBuilder_;

    /**
     * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
     */
    public java.util.List<com.ma.test.protobuf.gamedata2.gamedata1> getDatasList() {
      if (datasBuilder_ == null) {
        return java.util.Collections.unmodifiableList(datas_);
      } else {
        return datasBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
     */
    public int getDatasCount() {
      if (datasBuilder_ == null) {
        return datas_.size();
      } else {
        return datasBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
     */
    public com.ma.test.protobuf.gamedata2.gamedata1 getDatas(int index) {
      if (datasBuilder_ == null) {
        return datas_.get(index);
      } else {
        return datasBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
     */
    public Builder setDatas(
        int index, com.ma.test.protobuf.gamedata2.gamedata1 value) {
      if (datasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDatasIsMutable();
        datas_.set(index, value);
        onChanged();
      } else {
        datasBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
     */
    public Builder setDatas(
        int index, com.ma.test.protobuf.gamedata2.gamedata1.Builder builderForValue) {
      if (datasBuilder_ == null) {
        ensureDatasIsMutable();
        datas_.set(index, builderForValue.build());
        onChanged();
      } else {
        datasBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
     */
    public Builder addDatas(com.ma.test.protobuf.gamedata2.gamedata1 value) {
      if (datasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDatasIsMutable();
        datas_.add(value);
        onChanged();
      } else {
        datasBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
     */
    public Builder addDatas(
        int index, com.ma.test.protobuf.gamedata2.gamedata1 value) {
      if (datasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDatasIsMutable();
        datas_.add(index, value);
        onChanged();
      } else {
        datasBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
     */
    public Builder addDatas(
        com.ma.test.protobuf.gamedata2.gamedata1.Builder builderForValue) {
      if (datasBuilder_ == null) {
        ensureDatasIsMutable();
        datas_.add(builderForValue.build());
        onChanged();
      } else {
        datasBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
     */
    public Builder addDatas(
        int index, com.ma.test.protobuf.gamedata2.gamedata1.Builder builderForValue) {
      if (datasBuilder_ == null) {
        ensureDatasIsMutable();
        datas_.add(index, builderForValue.build());
        onChanged();
      } else {
        datasBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
     */
    public Builder addAllDatas(
        java.lang.Iterable<? extends com.ma.test.protobuf.gamedata2.gamedata1> values) {
      if (datasBuilder_ == null) {
        ensureDatasIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, datas_);
        onChanged();
      } else {
        datasBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
     */
    public Builder clearDatas() {
      if (datasBuilder_ == null) {
        datas_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        datasBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
     */
    public Builder removeDatas(int index) {
      if (datasBuilder_ == null) {
        ensureDatasIsMutable();
        datas_.remove(index);
        onChanged();
      } else {
        datasBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
     */
    public com.ma.test.protobuf.gamedata2.gamedata1.Builder getDatasBuilder(
        int index) {
      return getDatasFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
     */
    public com.ma.test.protobuf.gamedata2.gamedata1OrBuilder getDatasOrBuilder(
        int index) {
      if (datasBuilder_ == null) {
        return datas_.get(index);  } else {
        return datasBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
     */
    public java.util.List<? extends com.ma.test.protobuf.gamedata2.gamedata1OrBuilder> 
         getDatasOrBuilderList() {
      if (datasBuilder_ != null) {
        return datasBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(datas_);
      }
    }
    /**
     * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
     */
    public com.ma.test.protobuf.gamedata2.gamedata1.Builder addDatasBuilder() {
      return getDatasFieldBuilder().addBuilder(
          com.ma.test.protobuf.gamedata2.gamedata1.getDefaultInstance());
    }
    /**
     * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
     */
    public com.ma.test.protobuf.gamedata2.gamedata1.Builder addDatasBuilder(
        int index) {
      return getDatasFieldBuilder().addBuilder(
          index, com.ma.test.protobuf.gamedata2.gamedata1.getDefaultInstance());
    }
    /**
     * <code>repeated .gamedata2.gamedata1 datas = 1;</code>
     */
    public java.util.List<com.ma.test.protobuf.gamedata2.gamedata1.Builder> 
         getDatasBuilderList() {
      return getDatasFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ma.test.protobuf.gamedata2.gamedata1, com.ma.test.protobuf.gamedata2.gamedata1.Builder, com.ma.test.protobuf.gamedata2.gamedata1OrBuilder> 
        getDatasFieldBuilder() {
      if (datasBuilder_ == null) {
        datasBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ma.test.protobuf.gamedata2.gamedata1, com.ma.test.protobuf.gamedata2.gamedata1.Builder, com.ma.test.protobuf.gamedata2.gamedata1OrBuilder>(
                datas_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        datas_ = null;
      }
      return datasBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:gamedata2)
  }

  // @@protoc_insertion_point(class_scope:gamedata2)
  private static final com.ma.test.protobuf.gamedata2 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ma.test.protobuf.gamedata2();
  }

  public static com.ma.test.protobuf.gamedata2 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<gamedata2>
      PARSER = new com.google.protobuf.AbstractParser<gamedata2>() {
    public gamedata2 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new gamedata2(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<gamedata2> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<gamedata2> getParserForType() {
    return PARSER;
  }

  public com.ma.test.protobuf.gamedata2 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

