// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameMain.proto

package com.ma.test.protobuf;

public interface gamedataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gamedata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 row = 1;</code>
   */
  int getRow();

  /**
   * <code>int32 column = 2;</code>
   */
  int getColumn();

  /**
   * <code>repeated int32 data = 3;</code>
   */
  java.util.List<java.lang.Integer> getDataList();
  /**
   * <code>repeated int32 data = 3;</code>
   */
  int getDataCount();
  /**
   * <code>repeated int32 data = 3;</code>
   */
  int getData(int index);
}
