// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gamestart.proto

package com.ma.test.protobuf;

public interface nulldataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nulldata)
    com.google.protobuf.MessageOrBuilder {
}
