// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.ma.test.protobuf;

public interface testmsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:testmsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
